# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 62, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 71, 61))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 70, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 120, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.B_1 = QtWidgets.QPushButton(self.centralwidget)
        self.B_1.setGeometry(QtCore.QRect(130, 170, 93, 28))
        self.B_1.setObjectName("B_1")
        self.B_2 = QtWidgets.QPushButton(self.centralwidget)
        self.B_2.setGeometry(QtCore.QRect(130, 220, 93, 28))
        self.B_2.setObjectName("B_2")
        self.B_3 = QtWidgets.QPushButton(self.centralwidget)
        self.B_3.setGeometry(QtCore.QRect(130, 270, 93, 28))
        self.B_3.setObjectName("B_3")
        self.B_4 = QtWidgets.QPushButton(self.centralwidget)
        self.B_4.setGeometry(QtCore.QRect(130, 320, 93, 28))
        self.B_4.setObjectName("B_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 380, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 380, 61, 31))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 267, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Birinci Sayı"))
        self.label_2.setText(_translate("MainWindow", "İkinci Sayı"))
        self.B_1.setText(_translate("MainWindow", "Toplama"))
        self.B_2.setText(_translate("MainWindow", "Çıkarma"))
        self.B_3.setText(_translate("MainWindow", "Çarpma"))
        self.B_4.setText(_translate("MainWindow", "Bölme"))
        self.label_3.setText(_translate("MainWindow", "SONUÇ   :"))
